<div class="text-left section-header mt-1 ms-1">
    <b>My review of <?= $restaurant->name ?>:</b>
</div>
<div class="p-4">
    <div class="text-center text-success">
        <h4><?= $_SESSION['message'] ?? ''?></h4>
    </div>

    <div class="custom-inline p-4">

        <div class="text-center">

            <div class="section-header text-decoration-underline">
                <h4>header</h4>
            </div>
            <div class="mt-3">

                <b><?= $review->header ?></b>

            </div>

            <hr>

            <div class="section-header text-decoration-underline">
                <h4>content</h4>
            </div>
            <div class="mt-3">

                <p><?= $review->content ?></p>

            </div>
        </div>

        <hr>

        <div class="mt-5 text-center ">
            <a class="my-anchor bi-back float-start d-inline p-2" href="/restaurant/<?=$restaurant->url_name?>"> Restaurant</a>
            <a href="/edit_my_review/<?=$restaurant->url_name?>" class="my-anchor bi-pencil p-2"> Edit review</a>

            <form method="post" class="float-end" action="/delete_review/<?= $restaurant->url_name ?>">
                <input type="hidden" name="review-id" value="<?=$review->review_id?>">
                <button type="submit" class="bi-trash cancel-btn p-2"> Delete review</button>
            </form>
            
        </div>

    </div>
</div>


        
