<div class="py-4">

    <h4 class="text-center my-4">Share your opinion on <?= $restaurant->name ?></h4>

    <form method="post" action="/submit_new_review/<?=$restaurant->url_name?>">

        <div class="text-left custom-inline">

            <div class="custom-input">
                <h5>Header</h5>
                <input name="header" value="<?=htmlspecialchars($_POST['header'] ?? '') ?>" class="header" type="text"
                    placeholder="Header of your review">

                <div class="text-danger">
                    <?= $errors['header'] ?? '' ?>
                </div>

            </div>

            <div class="mt-4">
                <h5>Content</h5>
                <textarea name="content" class="content custom-textarea" rows="10"
                    placeholder="Content of your review"><?= htmlspecialchars($_POST['content'] ?? '') ?></textarea>

                <div class="text-danger">
                    <?= $errors['content'] ?? '' ?>
                </div>

            </div>

        </div>

        <input type="hidden" name="restaurant-id" value="<?=$restaurant->id?>">

        <div class="my-3 text-center ">
            <div class="custom-inline">
                <a class="bi-back my-anchor float-start d-inline p-2"
                href="/restaurant/<?=$restaurant->url_name?>"> Back</a>
                <button class="d-inline my-btn p-2" name="submit-review"
                type="submit" value="1">Submit my review</button>
            </div>
        </div>

    </form>
</div>
