<div class="text-center dashboard-header">
    <h1>Manage content</h1>
</div>

<div class="row p-5 text-center">

    <div class="col">
        <a class="dashboard-main-btn" href="/admin/restaurants">
            <div class="card p-2">
                <h3>Restaurants</h3>
            </div>
        </a>
    </div>

    <div class="col">
        <a class="dashboard-main-btn" href="/admin/keywords">
            <div class="card p-2">
                <h3>Keywords</h3>
            </div>
        </a>
    </div>

    <div class="col">
        <a class="dashboard-main-btn" href="/admin/users">
            <div class="card p-2">
                <h3>Users</h3>
            </div>
        </a>
    </div>

    <div class="col">
        <a class="dashboard-main-btn" href="/admin/reviews">
            <div class="card p-2">
                <h3>Reviews</h3>
            </div>
        </a>
    </div>
    
</div>